In [1]:
import snscrape.modules.twitter as sntwitter
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import matplotlib.pyplot as plt
%matplotlib inline

<h3> Data Collection </h3>

In [2]:
class exchange:
    def __init__(self, currency, currency_description, search_param):
        self.currency = currency
        self.currency_description = currency_description
        self.search_param = search_param

In [3]:
class exchange:
    def __init__(self, currency, currency_description, search_param):
        self.currency = currency
        self.currency_description = currency_description
        self.search_param = search_param

exchange_list = []
exchange_list.append(exchange('RUB', 'Russian Rouble ruble', 'rouble rub'))
exchange_list.append(exchange('TRY', 'Turkish Lira', 'turkish lira try'))
exchange_list.append(exchange('EUR', 'Euro', 'euro eur'))
exchange_list.append(exchange('GBP', 'Pound', 'pound gbp'))

In [4]:
def collect_tweets(exchange):
    tweets_list = []
    for i,tweet in enumerate(sntwitter.TwitterSearchScraper(exchange.search_param + ' since:2021-01-01 until:2021-02-01 lang:en').get_items()):
        tweets_list.append([tweet.user.username, tweet.content, tweet.date, tweet.likeCount,  exchange.currency, tweet])
    tweets_df = pd.DataFrame(tweets_list, columns=['Author', 'Text', 'Time', 'Like Count', 'Currency ISO Code', 'Url'])
    return tweets_df

In [5]:
all_twit_df = []
for exchange in exchange_list:
    ex_tweets_df = collect_tweets(exchange)
    all_twit_df.append(ex_tweets_df)
df = pd.concat(all_twit_df)
df

,Author,Text,Time,Like Count,Currency ISO Code,Url
0,yusobays,@elonmusk @elonmusk please Come to TRY₺ #turk...,2021-01-31 22:21:58+00:00,1,TRY,https://twitter.com/yusobays/status/1356004827...
1,BtcTurkDestek,"@DrBatal Hello, if you have registered using ...",2021-01-30 18:07:15+00:00,0,TRY,https://twitter.com/BtcTurkDestek/status/13555...
2,RisingValhalla,“I trade weekly bars. You?”\n\n200 day moving ...,2021-01-30 03:29:59+00:00,0,TRY,https://twitter.com/RisingValhalla/status/1355...
3,Erda55203615,@elonmusk Try turkish lira its at the bottom m...,2021-01-29 20:20:49+00:00,0,TRY,https://twitter.com/Erda55203615/status/135524...
4,Erda55203615,@ImTooRealForU TRY FUCKING TURKISH LIRA,2021-01-29 20:19:36+00:00,0,TRY,https://twitter.com/Erda55203615/status/135524...
...,...,...,...,...,...,...
844,flyingstocksman,For those of you who missed it last night with...,2021-01-01 09:24:17+00:00,0,GBP,https://twitter.com/flyingstocksman/status/134...
845,alpeshbp,GBP/USD Weekly Price Forecast – The British Po...,2021-01-01 07:13:32+00:00,0,GBP,https://twitter.com/alpeshbp/status/1344904575...
846,campsbay_com,"20.0142 ZAR for 1 GBP @ December 31, 2020 at 0...",2021-01-01 04:20:02+00:00,0,GBP,https://twitter.com/campsbay_com/status/134486...
847,MajorFXNow,GBP/EUR: Pound Lifted by UK Approval of AstraZ...,2021-01-01 02:32:32+00:00,0,GBP,https://twitter.com/MajorFXNow/status/13448338...
848,trader_blitz,GBP/JPY | $GBPJPY | $GBP $JPY\n\nBRITISH POUND...,2021-01-01 00:42:01+00:00,0,GBP,https://twitter.com/trader_blitz/status/134480...

In [6]:
df.to_csv('exchange_rates_dataset.csv', encoding='utf-8')

In [7]:
df = pd.read_csv('exchange_rates_dataset.csv')
df = df.drop(df.columns[0], axis=1)
df.head(100)

,Author,Text,Time,Like Count,Currency ISO Code,Url
0,yusobays,@elonmusk @elonmusk please Come to TRY₺ #turk...,2021-01-31 22:21:58+00:00,1,TRY,https://twitter.com/yusobays/status/1356004827...
1,BtcTurkDestek,"@DrBatal Hello, if you have registered using ...",2021-01-30 18:07:15+00:00,0,TRY,https://twitter.com/BtcTurkDestek/status/13555...
2,RisingValhalla,“I trade weekly bars. You?”\n\n200 day moving ...,2021-01-30 03:29:59+00:00,0,TRY,https://twitter.com/RisingValhalla/status/1355...
3,Erda55203615,@elonmusk Try turkish lira its at the bottom m...,2021-01-29 20:20:49+00:00,0,TRY,https://twitter.com/Erda55203615/status/135524...
4,Erda55203615,@ImTooRealForU TRY FUCKING TURKISH LIRA,2021-01-29 20:19:36+00:00,0,TRY,https://twitter.com/Erda55203615/status/135524...
...,...,...,...,...,...,...
95,HYCM,"💶💵EUR/USD climbs to session highs near 1.2140,...",2021-01-29 12:11:57+00:00,0,EUR,https://twitter.com/HYCM/status/13551265329818...
96,Drsam87524811,Binance in an hour is opening DOGE trading by ...,2021-01-29 11:02:17+00:00,6,EUR,https://twitter.com/Drsam87524811/status/13551...
97,Drsam87524811,Binance in an hour is opening DOGE trading by ...,2021-01-29 10:59:15+00:00,1,EUR,https://twitter.com/Drsam87524811/status/13551...
98,Francesc_Forex,Citibank 6/9: and expect Jan payrolls to rise ...,2021-01-29 10:34:13+00:00,0,EUR,https://twitter.com/Francesc_Forex/status/1355...
99,3Sigmamarkets,EURO ZONE CENTRAL BANKS' SOURCES DOWNPLAY CONC...,2021-01-29 10:28:06+00:00,0,EUR,https://twitter.com/3Sigmamarkets/status/13551...

In [8]:
df["target"] = ''
df['Time']= pd.to_datetime(df['Time'])
df["target"] = pd.to_numeric(df["target"])
df.dtypes

Author                            object
Text                              object
Time                 datetime64[ns, UTC]
Like Count                         int64
Currency ISO Code                 object
Url                               object
target                           float64
dtype: object

<h3> Exchange Rates of January 2021 </h3>

In [9]:
report_dataset = pd.read_excel('exchange_rates.xlsx', skiprows=[0])
report_dataset['Date'] = pd.to_datetime(report_dataset['Date'])
report_dataset.head(100)

         Date        RUB       GBP       TRY       EUR
0  2021-01-31  75.723385  0.728271  7.314766  0.823995
1  2021-01-30  75.723385  0.728271  7.314766  0.823995
2  2021-01-29  75.723385  0.728271  7.314766  0.823995
3  2021-01-28  76.407410  0.732801  7.386734  0.827061
4  2021-01-27  75.718838  0.729693  7.391613  0.825491
5  2021-01-26  75.149304  0.730446  7.351478  0.823520
6  2021-01-25  75.438776  0.730744  7.395079  0.822910
7  2021-01-24  74.930827  0.732398  7.418572  0.822504
8  2021-01-23  74.930827  0.732398  7.418572  0.822504
9  2021-01-22  74.930827  0.732398  7.418572  0.822504
10 2021-01-21  73.726682  0.728944  7.365932  0.822504
11 2021-01-20  73.617883  0.731865  7.446575  0.826378
12 2021-01-19  73.722387  0.734421  7.439581  0.824266
13 2021-01-18  74.263345  0.738337  7.505471  0.828912
14 2021-01-17  73.444197  0.734125  7.438670  0.824878
15 2021-01-16  73.444197  0.734125  7.438670  0.824878
16 2021-01-15  73.444197  0.734125  7.438670  0.824878
17 2021-01-14  73.482349  0.733611  7.381392  0.824810
18 2021-01-13  73.800674  0.731407  7.441312  0.821963
19 2021-01-12  74.051229  0.735466  7.487049  0.822301
20 2021-01-11  74.658801  0.741881  7.444709  0.822166
21 2021-01-10  74.122449  0.735739  7.358857  0.816327
22 2021-01-09  74.122449  0.735739  7.358857  0.816327
23 2021-01-08  74.122449  0.735739  7.358857  0.816327
24 2021-01-07  74.291300  0.734686  7.330319  0.814598
25 2021-01-06  73.607959  0.734600  7.339439  0.810504
26 2021-01-05  74.705810  0.736150  7.390922  0.814930
27 2021-01-04  73.472674  0.733247  7.366542  0.813273
28 2021-01-03  74.539239  0.732646  7.426534  0.814930
29 2021-01-02  74.539239  0.732646  7.426534  0.814930
30 2021-01-01  74.539239  0.732646  7.426534  0.814930
31 2020-12-31  74.539239  0.732646  7.426534  0.814930

In [10]:
report_dataset.dtypes

Date    datetime64[ns]
RUB            float64
GBP            float64
TRY            float64
EUR            float64
dtype: object

<h4>Calculating the change of exchange rate from time to the following day by following equation:</h4>

<img src="" width=200 height=200 />

In [11]:
def calculate_percentage_change_of_exchange_rate(day, previous_day):
    val = (day / previous_day) - 1 
    if val < 0:
        return -1
    elif val > 0:
        return 1
    else:
        return val

In [12]:
for (rowNo, rowData) in df.iterrows():
    try:
        day = (pd.to_datetime(rowData.values[2])).date().strftime('%Y-%m-%d')
        df_day = report_dataset[(report_dataset['Date'] == day)]
        
        previous_day = (pd.to_datetime(rowData.values[2])).date() + timedelta(days=-1)
        df_prev_day = report_dataset[(report_dataset['Date'] == previous_day.strftime('%Y-%m-%d'))]
        
        if rowData.values[4] == 'TRY': 
            val_first = df_day['TRY'].values[0];
            val_prev = df_prev_day['TRY'].values[0];
            df.loc[rowNo, 'target'] = calculate_percentage_change_of_exchange_rate(val_first, val_prev)
        elif rowData.values[4] == 'EUR': 
            val_first = df_day['EUR'].values[0];
            val_prev = df_prev_day['EUR'].values[0];
            df.loc[rowNo, 'target'] = calculate_percentage_change_of_exchange_rate(val_first, val_prev)
        elif rowData.values[4] == 'GBP': 
            val_first = df_day['GBP'].values[0];
            val_prev = df_prev_day['GBP'].values[0];
            df.loc[rowNo, 'target'] = calculate_percentage_change_of_exchange_rate(val_first, val_prev)
        elif rowData.values[4] == 'RUB': 
            val_first = df_day['RUB'].values[0];
            val_prev = df_prev_day['RUB'].values[0];
            df.loc[rowNo, 'target'] = calculate_percentage_change_of_exchange_rate(val_first, val_prev)


    except Exception as e:                                                                          
        print("An error occurred : ", e)

In [13]:
df

,Author,Text,Time,Like Count,Currency ISO Code,Url,target
0,yusobays,@elonmusk @elonmusk please Come to TRY₺ #turk...,2021-01-31 22:21:58+00:00,1,TRY,https://twitter.com/yusobays/status/1356004827...,0.0
1,BtcTurkDestek,"@DrBatal Hello, if you have registered using ...",2021-01-30 18:07:15+00:00,0,TRY,https://twitter.com/BtcTurkDestek/status/13555...,0.0
2,RisingValhalla,“I trade weekly bars. You?”\n\n200 day moving ...,2021-01-30 03:29:59+00:00,0,TRY,https://twitter.com/RisingValhalla/status/1355...,0.0
3,Erda55203615,@elonmusk Try turkish lira its at the bottom m...,2021-01-29 20:20:49+00:00,0,TRY,https://twitter.com/Erda55203615/status/135524...,-1.0
4,Erda55203615,@ImTooRealForU TRY FUCKING TURKISH LIRA,2021-01-29 20:19:36+00:00,0,TRY,https://twitter.com/Erda55203615/status/135524...,-1.0
...,...,...,...,...,...,...,...
1944,flyingstocksman,For those of you who missed it last night with...,2021-01-01 09:24:17+00:00,0,GBP,https://twitter.com/flyingstocksman/status/134...,0.0
1945,alpeshbp,GBP/USD Weekly Price Forecast – The British Po...,2021-01-01 07:13:32+00:00,0,GBP,https://twitter.com/alpeshbp/status/1344904575...,0.0
1946,campsbay_com,"20.0142 ZAR for 1 GBP @ December 31, 2020 at 0...",2021-01-01 04:20:02+00:00,0,GBP,https://twitter.com/campsbay_com/status/134486...,0.0
1947,MajorFXNow,GBP/EUR: Pound Lifted by UK Approval of AstraZ...,2021-01-01 02:32:32+00:00,0,GBP,https://twitter.com/MajorFXNow/status/13448338...,0.0
1948,trader_blitz,GBP/JPY | $GBPJPY | $GBP $JPY\n\nBRITISH POUND...,2021-01-01 00:42:01+00:00,0,GBP,https://twitter.com/trader_blitz/status/134480...,0.0

In [14]:
df.describe()

        Like Count       target
count  1949.000000  1949.000000
mean      2.415085     0.086711
std      47.000574     0.860479
min       0.000000    -1.000000
25%       0.000000    -1.000000
50%       0.000000     0.000000
75%       1.000000     1.000000
max    2054.000000     1.000000

In [15]:
df['Currency ISO Code'].value_counts()

EUR    1064
GBP     849
TRY      36
Name: Currency ISO Code, dtype: int64

In [16]:
df.to_csv('sentiment.csv', encoding='utf-8')